---
- hosts: localhost
  become_method: sudo
  remote_user: ec2-user
  become: yes
  become_user: root
  gather_facts: true
  vars:
    - Env1: ''
    - Build: ''
    - Artifactory: ''
    - Continuous_Integration: ''
    - Monitoring: ''
    - maven_instance_type: ''
    - artifact_instance_type: ''
    - jenkins_instance_type: ''
    - sensu_instance_type: ''
    - Log_monitoring: ''
    - elk_instance_type: ''
  vars_files:
    - vars1/main.yml
  roles:
    - { role: maven_creation, when: Build == 'Maven' }
    - { role: artifact_creation, when: Artifactory == 'Jfrog' }
    - { role: jenkins_creation, when: Continuous_Integration == 'Jenkins' }
#    - { role: sensu_creation, when: Monitoring == 'Sensu' }
#    - { role: elk_creation_mgnt, when: Log_monitoring == 'Elk' }
    - role: refresh

- include: mgnt_bootstrap.yml
