---
- hosts: localhost
  become_method: sudo
  remote_user: ec2-user
  become: yes
  become_user: root
  gather_facts: true
  vars_files:
    - vars1/main.yml
- include: uat_creation.yml
- include: mgnt_creation.yml
- include: prod_creation.yml
  



 
