---
- hosts: spendcategory-dev
  tasks:
    - supervisorctl:
            name: cel:spendcategory
            state: stopped
      become: true

    - name: Checking if the spendcategory service is running
      wait_for:
        timeout: 30
        port: 8080
        delay: 5
        msg: Service failed to start

    - name: Checking if the resource directory exists
      stat:
        path: /home/ngaurav/spendcategory/resources/
      register: resource
    - debug:
        msg: "Path exists and is a directory"
      when: resource.stat.exists == true

    - name: Creating resource Directory if not present
      file:
        path: /home/ngaurav/spendcategory/resources/
        state: directory
      when: resource.stat.exists == false

    - name: Checking if the resource file exists
      stat:
        path: /home/ngaurav/spendcategory/resources/application-dev.properties
      register: properties
    - debug:
        msg: "File exists"
      when: properties.stat.exists == true

    - name: copying property files
      copy:
        src: /home/ngaurav/spendcategory/resources/application-dev.properties
        dest: /home/ngaurav/spendcategory/resources/application-dev.properties-{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}
        remote_src: yes
      when: properties.stat.exists == true

    - name: copying latest property file
      copy:
        src: /mnt/disk2/.jenkins/jobs/spendcategory/workspace/spendcategory/src/main/resources/application-dev.properties
        dest: /home/ngaurav/spendcategory/resources/application-dev.properties
        owner: ngaurav
        group: ngaurav
        mode: 0777

    - name: Checking if the backup directory exits
      stat:
        path: /dev/shm/eSource/Backup_Deployment/Artifacts/
      register: backup_path
    - debug:
        msg: "Path exists and is a directory"
      when: backup_path.stat.exists == true

    - name: Creating Backup Directory if not present
      file:
        path: /dev/shm/eSource/Backup_Deployment/Artifacts/
        state: directory
      when: backup_path.stat.exists == false

    - name: Checking if the backup spendcategory artifact exits
      stat:
        path: /dev/shm/eSource/Backup_Deployment/Artifacts/spendcategory-2.0.jar
      register: artifact
    - debug:
        msg: "Artifact exists"
      when: backup_artifact.stat.exists == true

    - name: Deleting Backup Artifact if present
      file:
        path: /dev/shm/eSource/Backup_Deployment/Artifacts/spendcategory-2.0.jar
        state: absent
      when: backup_artifact.stat.exists == true

    - name: Checking if the current deployment directory exits
      stat:
        path: /dev/shm/eSource/Current_Deployment/Artifacts/
      register: current_path
    - debug:
        msg: "Path exists and is a directory"
      when: current_path.stat.exists == true

    - name: Creating Current Deployment Directory if not present
      file:
        path: /dev/shm/eSource/Current_Deployment/Artifacts/
        state: directory
      when: current_path.stat.exists == false

    - name: Checking if the current artifact exists
      stat:
        path: /dev/shm/eSource/Current_Deployment/Artifacts/spendcategory-2.0.jar
      register: current_artifact
    - debug:
        msg: "Artifact exists"
      when: current_artifact.stat.exists == true

    - name: copying the Artifacts to Backup
      copy:
        src: /dev/shm/eSource/Current_Deployment/Artifacts/spendcategory-2.0.jar
        dest: /dev/shm/eSource/Backup_Deployment/Artifacts/
        remote_src: yes
      when: current_path.stat.exists == true

    - name: Deleting Current Artifact
      file:
        path: /dev/shm/eSource/Current_Deployment/Artifacts/spendcategory-2.0.jar
        state: absent
      when: current_path.stat.exists == true

    - name: setting variables for deployment
      set_fact: group_id="com.wlt.cel"
    - maven_artifact:
          group_id: "{{ group_id }}"
          artifact_id: 'spendcategory'
          repository_url: 'http://2.253.226.156:8081/artifactory/libs-release-local/'
          version: 2.0
          extension: jar
          username: admin
          password: password
          dest: "/dev/shm/eSource/Current_Deployment/Artifacts/"

    - name: Starting the spendcategory service
      supervisorctl:
        name: cel:spendcategory
        state: started
      become: true

    - name: Checking if the spendcategory service is running
      wait_for:
        timeout: 30
        port: 8080
        delay: 5
        msg: Service Inactive
      register: msg
      ignore_errors: yes

    - block:
        - mail:
            host: gateway.dhl.com
            port: 25
            from: ngaurav@czcholstc000160.prg-dc.dhl.com
            to: Sameer M<sameer.m@mindtree.com>
            subject: spendcategory Deployment is Successful
            body: 'Application Server is running with latest deployment files. Please check the URL and in case of any queries, reach out to DevOps team.'
          delegate_to: localhost
          when: "msg.state == 'started'"
          become: true
      rescue:
        - name: Rollback starts here
          file:
            path: /dev/shm/eSource/Current_Deployment/Artifacts/spendcategory-2.0.jar
            state: absent
          when: "msg.msg == 'Service Inactive'"

        - name: Copy the last deployed artifact
          copy:
            src: /dev/shm/eSource/Backup_Deployment/Artifacts/spendcategory-2.0.jar
            dest: /dev/shm/eSource/Current_Deployment/Artifacts/
            remote_src: yes
          when: "msg.msg == 'Service Inactive'"

        - name: Deleting Backup Artifact
          file:
            path: /dev/shm/eSource/Backup_Deployment/Artifacts/spendcategory-2.0.jar
            state: absent
          when: "msg.msg == 'Service Inactive'"

        - name: Starting the spendcategory service
          supervisorctl:
            name: cel:spendcategory
            state: started
          become: true
          when: "msg.msg == 'Service Inactive'"

        - name: Checking if the spendcategory service is running
          wait_for:
            timeout: 30
            port: 8080
            delay: 5
            msg: Service failed to start
          register: recheck

        - name: Mail notification if the service is not running
          mail:
            host: gateway.dhl.com
            port: 25
            from: ngaurav@czcholstc000160.prg-dc.dhl.com
            to: Sameer M<sameer.m@mindtree.com>
            subject: Spendcategory Deployment Failure -> Rollback Intiated and Completed
            body: 'Application Server has failed to run with latest deployment files, hence rollback has been initiated and completed. Now the server is running with previously deployed files. Please check the URL and in case of any queries, reach out to DevOps team.'
          delegate_to: localhost
          when: "msg.msg == 'Service Inactive'"
          become: true

        - name: Mail notification if the service is not running
          mail:
            host: gateway.dhl.com
            port: 25
            from: ngaurav@czcholstc000160.prg-dc.dhl.com
            to: Sameer M<sameer.m@mindtree.com>
            subject: Spendcategory rollback deployment failed!!
            body: 'Application Server has failed to run with rollback deployment files. Please reach out to DevOps team.'
          delegate_to: localhost
          when: "recheck.msg == 'Service failed to start'"
          become: true
