---
- name: installing apt-transport-https
  apt:
    pkg: apt-transport-https
    state: present
  sudo: yes

- name: installing ca-certificates
  apt:
    pkg: ca-certificates
    state: present
  sudo: yes

- name: installing curl
  apt:
    pkg: curl
    state: present
  sudo: yes

- name: installing software-properties-common
  apt:
    pkg: software-properties-common
    state: present
  sudo: yes

- apt_key: url=https://download.docker.com/linux/ubuntu/gpg state=present

- apt_repository: repo='deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable' state=present update_cache='yes'

- name: install docker
  apt:
    pkg: docker-ce
    state: present
  update_cache: yes
  sudo: yes

- name: install docker-compose
  apt:
    pkg: docker-compose
    state: present
  sudo: yes

- name: copy docker-compose file
  copy:
    src: docker-compose.yml
    dest: /root/
  sudo: yes

- name: start the docker stack
  docker_service:
     project_src: /root/
  sudo: yes
