---
- name: getting client ip address
  ec2_instance_facts:
      filters:
        "tag:Name": MySql
      region: us-west-2
  register: MySql
  delegate_to: localhost
- debug:
      var: MySql
- name: getting master ip address
  ec2_instance_facts:
    filters:
      "tag:Name": Sensu
    region: us-west-2
  register: Sensu
  delegate_to: localhost
- debug:
    var: Sensu
- name: template for sensu repo
  template:
    src: /root/dengine_creation/ansible/job_creation/env_creation/sensu_master_file/client_sensu_repo.txt
    dest: /etc/yum.repos.d/sensu.repo
- name: installing sensu
  yum:
    name: sensu
    state: latest
- name: template for client config file
  template:
    src: /root/dengine_creation/ansible/job_creation/env_creation/sensu_master_file/mysql/mysql_client_config.j2
    dest: /etc/sensu/conf.d/client.json
- name: template for rabbitmq config file
  template:
    src: /root/dengine_creation/ansible/job_creation/env_creation/sensu_master_file/mysql/mysql_rabbitmq_config.j2
    dest: /etc/sensu/config.json
- name: installing sensu plugins
  command: sensu-install -p cpu-checks
           sensu-install -p cpu-checks
           sensu-install -p disk-checks
           sensu-install -p memory-checks
           sensu-install -p nginx
           sensu-install -p process-checks
           sensu-install -p load-checks
           sensu-install -p vmstats
           gem install sensu-plugins-mailer
           sensu-install -p tomcat
           sensu-install -p mysql  
  args:
    chdir: /opt/sensu/embedded/bin/
- name: starting sensu-client
  service:
    name: sensu-client
    state: started

