---
- name: Finding the latest RHEL AMI id
  ec2_ami_find:
   name: "RHEL-7.4_HVM-*"
   region: "{{ec2_config.region}}"
  register: ami_find

- name: Creating EC2 Instance
  ec2:
    region: "{{ec2_config.region}}"
    aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
    zone: "{{ db_subnet.subnets[0].availability_zone  }}"
    keypair: "{{ec2_config.keypair}}"
    instance_type: "{{ec2_config.instance_type}}"
    image: "{{ami_find.results[0].ami_id}}"
    vpc_subnet_id: "{{ db_subnet.subnets[0].id }}"
    group: "{{ec2_config.group2}}"
    assign_public_ip: no 
    count: 1
    wait: yes
    instance_tags:
       Name: "{{ ec2_config.instance_tag_name2 }}"
       Env: dev
  register: ec2

- name: Debug instance
  debug: msg={{ item.private_ip }}
  with_items:
    - "{{ ec2.instances }}"

- name: Waiting for Instances to listen on port 22
  wait_for:
    state: started
    host: "{{ ec2.instances[0].private_ip }}"
    port: 22
    timeout: 320
