---
- name: installing add-ons
  yum:
   name: "{{ item }}"
   state: latest
  with_items:
    - gcc-c++
    - make

- name: downloading setup files
  get_url: 
     url: https://rpm.nodesource.com/setup_8.x
     dest: /tmp/setup_8.x

- name: executing setup files
  shell: bash /tmp/setup_8.x && touch /tmp/setup_8.x.done
  args:
    creates: /tmp/setup_8.x.done

- name: installing nodejs and npm
  yum:
   name: nodejs
   state: present
