---
#- hosts: localhost
#  user: ec2-user
#  become_method: sudo
#  connection: local
# gather_facts: false
# vars_files:
#   - vars/main.yml
# roles:
#    - ec2_creation
#    - refresh

- hosts: tag_Name_{{ec2_config.instance_tag_name}}
  remote_user: ubuntu
  become: yes
  become_user: root
  gather_facts: false
  vars_files:
    - vars/main.yml
  pre_tasks:
    - raw: apt install -y python-simplejson 

- hosts: tag_Name_{{ec2_config.instance_tag_name}}
  remote_user: ubuntu
  become: yes
  become_user: root
  vars_files:
    - vars/main.yml
  vars:
    nodejs_version: "6.x"
    pip_install_packages:
      - name: docker-py

  roles:
#    - geerlingguy.repo-epel
    - geerlingguy.git
    - geerlingguy.ansible
    - geerlingguy.docker
#    - geerlingguy.pip
    - geerlingguy.nodejs
    - geerlingguy.awx
  tasks:
   - name: creating dynamic inventory directory
     file:
       path: /etc/ansible/inventory
       state: directory

   - name: copying ec2.py file
     copy:
       src: files/ec2.py
       dest: /etc/ansible/inventory/ec2.py
       mode: 0777

   - name: copying ec2.ini
     template:
      src: files/ec2.ini.j2
      dest: /etc/ansible/inventory/ec2.ini
      mode: 0644

   - name: copying ansible roles
     synchronize:
       src: /etc/ansible/roles
       dest: /etc/ansible/

   - name: copying pem file
     copy:
       src: /root/.ssh/ansible.pem
       dest: /root/.ssh/ansible.pem
       mode: 0600

   - name: adding key to ssh_config
     lineinfile:
       path: /etc/ssh/ssh_config
       line: 'IdentityFile /root/.ssh/ansible.pem'

   - name: adding permissions to ssh_config
     lineinfile:
       path: /etc/ssh/ssh_config
       line: 'StrictHostKeyChecking no'

   - name: copying ansible.cfg
     copy:
       src: /etc/ansible/ansible.cfg
       dest: /etc/ansible/ansible.cfg
   
   - name: installing pip
     apt:
      name: "{{item}}"
     with_items:
      - python-pip
      - git

   - name: installing boto and awscli
     pip:
      name: "{{item}}"
     with_items:
      - boto
      - boto3
      - awscli
      - docker-py

   - name: configure aws access key id
     shell: aws configure set aws_access_key_id AKIAJ5BRP6OHXUHGRWKQ

   - name: configure aws secret access key
     shell: aws configure set aws_secret_access_key ASoXqDx19FIpYoQIoAr3IUvPPHNcny4ELrBAiKbz
  
   - name: configure aws secret access key
     shell: aws configure set default.region us-west-2


