---
- hosts: localhost
  user: ubuntu
  become_method: sudo
  connection: local
  gather_facts: false
  vars_files:
    - vars/main.yml
  roles:
    - vpc_create
    - web_create
    - db_create
    - refresh

- hosts: tag_Name_{{ ec2_config.instance_tag_name1 }}, tag_Name_{{ ec2_config.instance_tag_name2 }}
  become_method: sudo
  remote_user: root
  gather_facts: false
  vars_files:
    - vars/main.yml
  pre_tasks:
    - name: 'install python2'
      raw: yum install -y python

- hosts: tag_Name_{{ec2_config.instance_tag_name1 }}
  become_method: sudo
  remote_user: root
  gather_facts: true
  vars_files:
    - vars/main.yml
  roles:
    - devops.tomcat7 

- hosts: tag_Name_{{ ec2_config.instance_tag_name2 }}
  become_method: sudo
  remote_user: root
  gather_facts: true
  vars_files:
    - vars/main.yml
  roles:
    - geerlingguy.mysql

- hosts: tag_Name_{{ec2_config.instance_tag_name1 }}
  become_method: sudo
  remote_user: root
  gather_facts: true
  vars_files:
    - vars/main.yml
  roles:
    - connect
