---
- name: Installing java
  yum:
    name: java-1.8.0-openjdk-devel
    state: present
- name: adding contents to configuration file
  lineinfile:
    dest: /etc/profile
    line: "{{ item }}"
  with_items:
  - export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-0.b14.el7_4.x86_64
  - export PATH=$PATH:$JAVA_HOME/bin
  - export CLASSPATH=.:$JAVA_HOME/jre/lib:$JAVA_HOME/lib:$JAVA_HOME/lib/tools.jar
- name: updating the changes in configuration file
  shell: source /etc/profile
